order:
    path: /order/{id}
    methods: GET
    controller: App\Controller\HomeController::order

orders:
    path: /orders
    methods: GET
    controller: App\Controller\HomeController::orders

pasarela:
    path: /pasarela
    methods: POST
    controller: App\Controller\HomeController::pasarela

pedidos_index:
    path: /pedidos
    methods: GET
    controller: App\Controller\HomeController::pedidos

pre_order:
    path: /preorder
    controller: App\Controller\HomeController::preOrder

productos:
    path: /
    controller: App\Controller\HomeController::productos

producto_list:
    path: /producto/list/{id}
    methods: GET
    controller: App\Controller\ProductoController::list
