productos:
    path: /
    controller: App\Controller\HomeController::productos

pasarela:
    path: /pasarela
    methods: POST
    controller: App\Controller\HomeController::pasarela

orders:
    path: /orders
    methods: GET
    controller: App\Controller\HomeController::orders

pedidos_index:
    path: /pedidos
    methods: GET
    controller: App\Controller\HomeController::pedidos

pre_order:
  path: /preorder/{id}
  controller: App\Controller\HomeController::preOrder
