index:
    path: /
    controller: App\Controller\HomeController::index

productos:
    path: /productos
    controller: App\Controller\HomeController::productos

pasarela:
    path: /pasarela
    methods: POST
    controller: App\Controller\HomeController::pasarela

orders:
    path: /orders
    methods: GET
    controller: App\Controller\HomeController::orders